cp calculate_code_obf.js task_1_img/calculate_code_obf.js
cp calculate_code_obf.js task_28/calculate_code_obf.js
cp calculate_code_obf.js task_39/calculate_code_obf.js
cp calculate_code_obf.js task_1/calculate_code_obf.js
cp calculate_code_obf.js task_1_inline-tags/calculate_code_obf.js
cp calculate_code_obf.js task_29/calculate_code_obf.js
cp calculate_code_obf.js task_4/calculate_code_obf.js
cp calculate_code_obf.js task_10/calculate_code_obf.js
cp calculate_code_obf.js task_1_p/calculate_code_obf.js
cp calculate_code_obf.js task_3/calculate_code_obf.js
cp calculate_code_obf.js task_40/calculate_code_obf.js
cp calculate_code_obf.js task_11/calculate_code_obf.js
cp calculate_code_obf.js task_2/calculate_code_obf.js
cp calculate_code_obf.js task_30/calculate_code_obf.js
cp calculate_code_obf.js task_5/calculate_code_obf.js
cp calculate_code_obf.js task_12/calculate_code_obf.js
cp calculate_code_obf.js task_20/calculate_code_obf.js
cp calculate_code_obf.js task_31/calculate_code_obf.js
cp calculate_code_obf.js task_6/calculate_code_obf.js
cp calculate_code_obf.js task_13/calculate_code_obf.js
cp calculate_code_obf.js task_21/calculate_code_obf.js
cp calculate_code_obf.js task_32/calculate_code_obf.js
cp calculate_code_obf.js task_7/calculate_code_obf.js
cp calculate_code_obf.js task_14/calculate_code_obf.js
cp calculate_code_obf.js task_22/calculate_code_obf.js
cp calculate_code_obf.js task_33/calculate_code_obf.js
cp calculate_code_obf.js task_8/calculate_code_obf.js
cp calculate_code_obf.js task_15/calculate_code_obf.js
cp calculate_code_obf.js task_23/calculate_code_obf.js
cp calculate_code_obf.js task_34/calculate_code_obf.js
cp calculate_code_obf.js task_9/calculate_code_obf.js
cp calculate_code_obf.js task_16/calculate_code_obf.js
cp calculate_code_obf.js task_24/calculate_code_obf.js
cp calculate_code_obf.js task_35/calculate_code_obf.js
cp calculate_code_obf.js task_17/calculate_code_obf.js
cp calculate_code_obf.js task_25/calculate_code_obf.js
cp calculate_code_obf.js task_36/calculate_code_obf.js
cp calculate_code_obf.js task_18/calculate_code_obf.js
cp calculate_code_obf.js task_26/calculate_code_obf.js
cp calculate_code_obf.js task_37/calculate_code_obf.js
cp calculate_code_obf.js task_19/calculate_code_obf.js
cp calculate_code_obf.js task_27/calculate_code_obf.js
cp calculate_code_obf.js task_38/calculate_code_obf.js